repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.6.3'
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: json-schema-validation
        name: JSON Schema Validation
        entry: uv run src/prefect_collection_registry/view_schema_validation.py
        language: system
        pass_filenames: false
        types: [json]
