[project]
name = "prefect-collection-registry"
version = "0.1.0"
description = "Maintaining the Prefect Collection Registry"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect@git+https://github.com/PrefectHQ/prefect.git",
    "fastjsonschema==2.16.2",
    "gh-util",
]
