[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "prefect-collection-registry"
authors = [
    {name = "Prefect Technologies", email = "help@prefect.io"},
]
description = "Maintaining the Prefect Collection Registry"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "prefect>=2.13.5",
    "fastjsonschema==2.16.2",
    "github3.py>=3.2.0",

]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest", "coverage", "prefect-kubernetes"]
