name: Ensure JSON views are valid on PR
on:
  pull_request:
    branches:
      - main
    paths:
      - 'views/**'
      - '.github/workflows/json-validation.yml'

jobs:
  submit-update-pr:
    name: Run JSON schema validation against all views
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Add utils to PATH
        run: |
          echo "$GITHUB_WORKSPACE/src/utils" >> $GITHUB_PATH

      - name: Run JSON schema validation
        run: |
          python scripts/view_schema_validation.py