name: PR Views to PrefectHQ/prefect

on:
  push:
    branches:
      - main
    paths:
      - "views/aggregate-worker-metadata.json"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PREFECT_PRS_RW }}

jobs:
  update-views:
    name: Send updated views to PrefectHQ/prefect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Sync views to core
        run: uv run --frozen src/prefect_collection_registry/sync_views_to_core.py 
