---
name: Build and publish Prefect Integrations (workspace) Deployments

"on":
  push:
    branches:
      - main
    paths:
      - .github/workflows/prefect-deploy-integrations.yaml
      - prefect.yaml
      - src/**
  pull_request:
    paths:
      - .github/workflows/prefect-deploy-integrations.yaml
      - prefect.yaml
      - src/**

  workflow_dispatch: {}

# Limit concurrency by workflow/branch combination.
#
# For builds, pushing additional changes to the
# branch will cancel prior in-progress and pending builds.
#
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Do not grant jobs any permissions by default
permissions: {}

env:
  PREFECT_API_URL: ${{ secrets.PREFECT_PRD_INTEGRATIONS_WORKSPACE_API_URL }}
  PREFECT_API_KEY: ${{ secrets.PREFECT_PRD_INTEGRATIONS_WORKSPACE_API_KEY }}

jobs:
  deploy_flows:
    name: Build integrations workspace deployment images
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
      # required to obtain Google Cloud service account credentials
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GHA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: collection-registry-gen-main@prefect-org-github-actions.iam.gserviceaccount.com

      - name: Configure Google Cloud credential helper
        run: gcloud auth configure-docker --quiet us-docker.pkg.dev
      
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Deploy all integrations flows
        run: uv run prefect --no-prompt deploy --all
